### ISSUE TITLE
dead link in api-documentation/guides/_event-api.md

### ISSUE THREAD

**Issue by SergeySch** [mailjet/api-documentation#23]
Hi, 
[Event API: real-time notifications](https://github.com/mailjet/api-documentation/blob/master/guides/_event-api.md#online-demonstration) page has dead link to [Mailjet Live Event API Dashboard](https://live-event-dashboard-demo.mailjet.com/) ( https://live-event-dashboard-demo.mailjet.com/ )in last "Online Demonstration" section.

Best,
Serhii

**Comment by adamyanliev** [comment]
Hey @SergeySch , thanks for letting us know. 

The Event API Dashboard demo was actually discontinued - that's why the link is dead. We removed it from the guide with one of the latest updates. I've just updated the Email API files in this repo to the currently released version, so the Online Demo section is removed here as well.

Best regards,
Atanas
